### ISSUE TITLE
AttributeError: MacOsStravaImgUpdater instance has no attribute 'keyPairId'

### ISSUE THREAD

**Issue by csytsma** [solitone/josm_strava_cookies#1]
First, thanks so much for writing this tool. I've grown very tired of manually doing this every 2 weeks, and was also thinking of a way to automate it.

Steps to Reproduce:
1. In Safari, login to Strava and check Remember Me.
2. Go to https://www.strava.com/heatmap
3. In terminal, run script: `python upd_strava_prefs.py`

Full error:
`Traceback (most recent call last):
  File "upd_strava_prefs.py", line 12, in <module>
    stravaImgUpdater.getCookies()
  File "/Users/<user>/Development/josm_strava_cookies-master/stravaImgUpdater.py", line 54, in getCookies
    if (self.keyPairId == "" or self.policy == "" or self.signature == ""):
AttributeError: MacOsStravaImgUpdater instance has no attribute 'keyPairId'`

Python: 2.7.10
Safari: Version 12.0 (14606.1.36.1.9)
JOSM: 14824
JOSM Imagery: `tms[3,15]:https://heatmap-external-{switch:a,b,c}.strava.com/tiles-auth/all/hot/{zoom}/{x}/{y}.png`

**Comment by csytsma** [comment]
The issue appears to not having permission for the `~/Library/Cookies/Cookies.binarycookies` file.  I had to manually copy the cookie file to a new location, such as my Desktop. 

I then updated `stravaImgUpdater.py` line 43 to reference my Desktop instead of the Library location, then it worked for me.

I tried to change permissions of the `~/Library/Cookies/Cookies.binarycookies` file using sudo chmod, and was not able to. Not sure why.

**Comment by csytsma** [comment]
Issue is MacOS's extended security permissions. You have to enable permission for your terminal app to access the file.  Instructions here: http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

**Comment by solitone** [comment]
Hi, sorry for my late reply, and thank you for your comments.

Could you please confirm that what I wrote in the README clears this up? Usage instruction #6:

> Grant Terminal with full disk access (macOS System Preferences > Security & Privacy > Privacy > Full Disk Access > Add the Terminal application).

**Comment by csytsma** [comment]
That looks correct.
