### ISSUE TITLE
No Strava Cookies found!

### ISSUE THREAD

**Issue by Martin868** [solitone/josm_strava_cookies#2]
I updated the scripts and ran it again. Now I get this error. I can confirm I did login in to Strava and the Stava Heatmap site, and check the Remember Me box. Despite that the script do es not pick a cookie to work with.

Error message I get: 
"No Strava cookies found!
Open Safari, browse to the Strava Heatmap, and login with your Strava account."

**Comment by solitone** [comment]
Hi, and sorry for my late reply.

Could you please confirm that you can address this issue by following usage instruction #6?

> Grant Terminal with full disk access (macOS System Preferences > Security & Privacy > Privacy > Full Disk Access > Add the Terminal application).

**Comment by Martin868** [comment]
Yes this worked. Thanks. 

Martin Chalifoux
E martin.chalifoux@icloud.com
C 514-233-9701
