### ISSUE TITLE
Generalize to other browsers / OSes; Python3

### ISSUE THREAD

**Issue by smootheFiets** [solitone/josm_strava_cookies#3]
Thanks so much for writing this tool!  I find Strava's high-res heatmaps incredibly useful for mapping, yet the process of reading out cookie information is something that computers are much better at than humans... 🥇 

Having said that, I don't use Safari on my Mac if I can help it.  I also use Linux machines.  And Python2 is dying.  

So, I had a crack at generalizing your software.  I'll create two pull requests in a minute: one to allow Chrome and Firefox on OSX, the second porting everything to Python3.  Expect a third PR soon, which should allow the tool to be run under Linux (if I understand correctly, this should be as easy as defining a new subclass in which the path to JOSM preferences is defined).  More detail within the PRs.  Let me know what you think!

**Comment by solitone** [comment]
Thank you and sorry for not replying before! Very interesting, I need to check it out and test it. Cheers!

**Comment by solitone** [comment]
First, I need to understand what action should I perform to merge your deltas. I haven't used git for a while..

**Comment by solitone** [comment]
Very nice work, thank you again indeed. Unfortunately I haven't tested it under linux or windows yet, but everything seems fine. Hopefully some other user will give us some feedback.

**Comment by solitone** [comment]
I've tested on Windows 10 / Chrome and works just fine. I just need to fix some minor issues related to error messages that need to be sent to stderr rather than stdout, but it's a problem affecting all code that was inherited from the original basecode.
